### ISSUE TITLE
Simplify groove settings dialog

### ISSUE THREAD

**Issue by HertzDevil** [HertzDevil/0CC-FamiTracker#25]
- [x] plain text edit control
- [x] remove copy / paste
- [x] add "copy as pattern"
- [ ] add "get from selection"?
