### ISSUE TITLE
Compatibility mode

### ISSUE THREAD

**Issue by HertzDevil** [HertzDevil/0CC-FamiTracker#32]
- [ ] check version of current FTM
- [ ] report on detecting unsupported feature
- [ ] enforce compatibility while modifying FTM
- [ ] disable unsupported features
- [ ] remove incompatible data from current FTM or saved FTM
- [ ] separate i/o methods from CFamiTrackerDoc
- [ ] configuration tab
