### ISSUE TITLE
Disable selection operations when skip effects are present or when selection contains the same pattern in more than one frame

### ISSUE THREAD

**Issue by HertzDevil** [HertzDevil/0CC-FamiTracker#4]
Consider a selection spanning across two adjacent frames:

Row|Note|Inst|Vol|fx1
---|---|---|---|---
2E|C-3|||462
2F||||D00
30-3F|...|...|...|...
00||||
01||||
02|D-3|||464

- [ ] Drag paste (may move skip effects to other frames)
- [x] Interpolate (may overwrite effects in between)
- [x] Reverse (may move skip effects to other frames)
- [x] Expand (may move skip effects to other frames)
- [x] Shrink (may remove lines containing skip effects)

**Comment by HertzDevil** [comment]
done as selection condition; drag paste to be handled later
