### ISSUE TITLE
Interface improvements in 0.5.0 beta 5

### ISSUE THREAD

**Issue by HertzDevil** [HertzDevil/0CC-FamiTracker#47]
- [ ] Display average BPM
- [ ] Display channel state
- [ ] Registry entry for "Display register state"
- [ ] Movable octave bar
- [ ] Control panel position
- [ ] Meter decay rate setting
- [ ] Registry entry for frame editor font
- [ ] Save/load appearance settings
- [ ] Pattern editor row marker (bookmark)
- [ ] Mixer reset button
